language: node_js
node_js:
- node
deploy:
  api_key:
    secure: bGO9nC5iY6lUxdaJvFyol1kYCeoP09okF3n240zNil+2X0SYil2Wu7sQjVqza2DIF3yk1tkX0HmzHm5rpN7s0gLRN9e0oMz3tU+X4P0gsmr/Uy+Hh2mLDcM+dV2w6IyR97PNwhYSyZMsF8GTeR+26+Md6sFRTkmQqq/l4ueyX+OuBqYPnvi34yuKkBzwhXwl+lC0rjm8S2MJ+LWor88opxt8QptZXicCnyaCO4Hs2++bnxecBOos4mPtJh10uM8n4Epvu95pplkf5qTris8S++/Xp1bDb6yZK6+GSTE6vH/KT4W6EoX69Derxh9v/OJnS+ocpXbzQ8CSrbJdweXrBucFCyLKrJqjNVsllIulzEQ2IZcG5xN7BI8zuTxXyOt4ZZ4XE/5aLo9G7ZZQa2Dx2znVOpMincCgKmEuIB/uVZGFDMk1DxLteimFxlhGHSGMPjZyiL+HIzM1KQrDAEXLDyCXQTwEUKearXhyfteO0+IMFP+bajt5GJlt5zuQxTi6vPz8W8u9lMlf/hnEdWKPFYTMULPXRgsA0yQCY/WGB5n0KBKTHAcd8D8lQAwjbtBRCACA4ptrPSTF//OpgLUI3nygePaKQaP/PX9/CRdwp6SybmkoofCv/Z+Fd3UlFrXlPJorLF6maRj2my+arLB+DbbSJKyToiKlt1MjicvHD1U=
