language: node_js
node_js:
- node
deploy:
  api_key:
    secure: QfhoxvKNPR8WrpiTcUBa/B8AMaecptrWPsYq9x1W0gQa82c/8edMwy9rZNDl7qlGOGs51v1DGDMGu3SK61uwj7XDsU8SoOiRFG0Wg7S7SRLhsQuN6EGPujncPsrpdrNZoX4grvPB5CQ+h234ujNJPEEJzRhkqOr9unytQ30fnqJQzJH4wz5oRcDXbxWdjxB2uftz7iqlDFt7n8YY+v/Kg3MZxczScUvo/QQpnwATMr6SRp7ksOX5ebwWozZUO1HAjiqZjJbwUQNlGRt2AFXe/w4FX3XliveXgt2SDM/17x5oqaUqqxtHIh+R29iEIHdW6qwMZCToJNkgk4Fwp253qGcrPkwuCWnIpa8DxQGgfZF5glJHF9gSYNVZAvSWuj7cuw4MmyKy4GE+teP0vB3S/EnZc+aE2MQvnfBP/3KCzUQNwux++ACfrMojqUJzT3kn0M5zb5E6kJt0oWaBKK7z3KXD/vMq3HtOpn2VbSkxW6T1VuXthKSSnCwvv+MOmV+9KVLRLcKGL/VGrvOiGqXH167Sm3E+iofaADiK4rqJo9edQuTTtEmMF7WpYwDo9twLMUnhgq+fM01nWCAzZT5PKgZfizCu4QfmG+FaVvhFvdWXRAX7r/R7hd6LKjT91vOCYEs+8Pa1UZimSbqYWUYPQ1MPWsIVuzbgKhFWmI8L1Is=
