language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: HWDw7E7gfaE5XbS/JKr2k9djB+FDZc9+Jh/YBkYGfo9CB3BdOd1slj8zqwlt0795i21JzbsP0QjSmjnS5aysSpoHjdd5MOsY0f6fC7T6Kl5pBUZb9U80rbJ14hW5CFB89DcqiZay5d/BpV8f6GYicNoj5P34Reyr/a/nTG+UsQs9pMhS9yGJHz39Hl5CNQmjyUiP5gjW92ysQ9EaRGpv7pFox/EnWAvjs2SJ0ZHHTz6FgqQ3xUE+qpcxRmFQxN9Xobc7Uaz2JErwp6S+0UtFz2TCxy13g61rIR6UHGrP2HO4HU7Ki8dzOLohYdfpnyOX6urxGLydWOZTJqX+oWTIGz0h/ll9znAdDfk7RK66IjokNUs5U7lHSDnCq8tosjZno1hQ5eflIMMh/fLzhCLsBgcYOZPrM7jMK3yzfDY/0I3CM4yOY5uNKpcJZEjr5OFgVqVeqCGvakLapZR/esmfJWYuaULpb8nLdjSrd01W5F+m3O43eZzQTy12r6OoIKPgPDQpUHQj4HIUgsG9TbcCnNtUsHZDNsThIpJPHZeJrrwVx+5A2E+XrQEtIZJVL0lY+q+1EcAs2pd2gyEfiHRJ3MZTIMVseATl4f5B40gXBK2fhACWClQZNz35p9L5GAMCRkLluL8qPhckLEdmUpTwyZyJeLiUb1jRmKxOVkupgoc=
