language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: AtxEC/MXmh3Hpj9cTerohFwuF/aCwg2oqAVO7mtlXKFLbtDeapIL0PDhiW2wjwTng2pne6ubkeV7D7EezJLqvOmaPSv/0i82+XPOb3NUXHGUwesdhbu65g+1FjCu5/oHiglZal27ikdDHLjqigxzHavQNrW5JE3fWD/VUoCTGYHzheNQpfufJie9jDahY9ouIk1WKOt3b2OmX4fbn3ZH9h0HCbRoxyk9zcFkqAtBL98L81xN3D0HP/Mc2aoChuZjvWp1GYa5H6Tffrdujkq57hC44Kd0HnLL04TTlvhwV9Zl+GM6qWiFATSZUDi4TGsE9h2kTv6Tj1WAUvuKk0zzlvTkDqS5Usavc83QcXLBde5F46V1hJJXoNFo/koZ1pfuq/6USpgE2F/IJZnImQkYFvNQJJx4aQ7j2DKpC7eD0JNa3JSuZsHo3MpIA6gwMBpjYZTCiUXBo3V+KYS1GZXZf6TGOypUPryU6cJ65ZEjZn3ZUnVHaLD97VbxH6p7dgD3Diaob0j2Wn7yF0yvPhQuNREzDP6VgU8GpasdnnShGPt0MYTB/sf0TM6XPzhqHBQMFjGQs+/6KD7ZUOQcOKY5NliEYl54qkSEj6pHd0BnshIs+XLJyWGvi32BjsNFzz6yBTMesiH51f7OtS6/O4y8DKXQ0COLz40n5IErhse8bZI=
  app: secure-hamlet-10442
