language: node_js
node_js:
- node
deploy:
  api_key:
    secure: SXKvqQeJqf3uiE+7wXWdZFTOG/iHdqM2JipahqkJR2xEXylPPFydvZAE5LMv3lN9eeY3cdFCz+kUI6k1DPE66qex8BjmMsbQT/okX3sUIEncVSfIMc6791s7+JqKpBB3xzMffZoCMmfMDeoz0rKBupJryRFzUaYQokon7T+7FqiINM7svLJqU6/a6B6f8Ke7cYf68xUcGAmC6ndQD6C51iptm6EFfuXpIBnts80EilIGHW6vZukfzoUQyTRs/ak3Bc6sGDakO6HGjeGHN3AgA0xwy8v/QSWIoJP3aa/x2EkGO429W25wp7j2oguBeR0sAQ1eah5fPHUK30t9Qa4YqzTpEIdhee9wj62QXcZHBVJiI8osPjkmJglBsFm5+M2aD90uTPegmh/hhnAWoqdaObYKSZT5DeTHFD0BMtk80zvw4RQj54wSw5LUJBInwIds5wn3wDJ8FivGYyZ0b104Fr7zYoUhY0O0ZgDZoZmRLng1MWiE+0wDKhm0dHBerNI+NSfK4vObrd3A1OcV8lTi0L04pQFEWSEp31e2S3o6VjZjx8N1s1ILqeQXcNdB1/lumQHhhnr7RaHrE7dnuLmLVqoVPdCo0qpHQAcbLOy7pzw2Lo8d4u267OfdcHnKAKG3+pm6fqDHJM+QtzLFjr/hg0tsjnLor1bpHuzRQ7Mav3A=

